#!/bin/bash

##Tested on:

#- Raspbian (RaspberryPi - think of those possibilities)

if [ "$(whoami)" != "root" ] ; then
    echo -e "You must run this script as root."
    end
fi

###################################
# install Django #
###################################
echo -e "\nInstalling django \n"
if sudo pip install django ; then
    echo -e "    Successfully installed django runtime \n"
else
    echo -e "    Failed to installed django."
    end
fi

###################################
# Enable I2C1 #
###################################
# Add lines to /boot/config.txt
echo -e "\nEnalbe I2C..."
egrep -v "^#|^$" /boot/config.txt > config.txt.temp  # pick up all uncomment configrations
if grep -q 'dtparam=i2c_arm=on' config.txt.temp; then  # whether i2c_arm in uncomment configrations or not
    echo -e '    Seem i2c_arm parameter already set, skip this step \n'
else
    echo -e '    dtparam=i2c_arm=on \n' >> /boot/config.txt
fi
rm config.txt.temp
echo -e "    Done\n"

###################################
# Startup Dragit #
###################################
echo -e "\nSetting up Dragit..."
cd bin
sudo chmod +x dragit
sudo cp dragit /etc/init.d/dragit

sudo update-rc.d dragit defaults

echo -e "    Done \n"
